package org.java.programs.beginner;


/* 389. Find the Difference
 * You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * Example 1:
 * Input: s = "abcd", t = "abcde"   | Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 */


import java.util.HashMap;

public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        int charCode = 0;
        for (char c : s.toCharArray()) {
            charCode ^= c;
        }
        for (char c : t.toCharArray()) {
            charCode ^= c;
        }
        return (char) charCode;
    }

    public char findTheDifferenceUsingSum(String s, String t) {
        int sumS = 0;
        int sumT = 0;

        for (char c : s.toCharArray()) {
            sumS += c;
        }
        for (char c : t.toCharArray()) {
            sumT += c;
        }

        return (char) (sumT - sumS);
    }

    public char findTheDifferenceUsingHashMap(String s, String t) {
        HashMap<Character, Integer> charCount = new HashMap<>();

        for (char c : s.toCharArray()) {
            charCount.put(c, charCount.getOrDefault(c, 0) + 1);
        }
        for (char c : t.toCharArray()) {
            charCount.put(c, charCount.getOrDefault(c, 0) - 1);
            if (charCount.get(c) < 0) {
                return c;
            }
        }
        return '\0'; // This line should never be reached
    }

    public static void main(String[] args) {
        FindTheDifference ftd = new FindTheDifference();
        String s1 = "abcd";
        String t1 = "abcde";
        System.out.println("The difference character is: " + ftd.findTheDifference(s1, t1));

        String s2 = "";
        String t2 = "y";
        System.out.println("The difference character is: " + ftd.findTheDifferenceUsingSum(s2, t2));

        String s3 = "aabbcc";
        String t3 = "abcbcad";
        System.out.println("The difference character is: " + ftd.findTheDifferenceUsingHashMap(s3, t3));
    }
}
